=== abc2cobsubasrikavya/100FIT_BOBE/BOBE_ouputgenerated/BoschInputs/hexmodx/resources/schemas/rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Varuna.A.L (Robert Bosch India Limited) -->
<!--W3C Schema generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<xs:schema targetNamespace="www.rbin.com/mds-1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="www.rbin.com/mds-1" elementFormDefault="qualified">
	<xs:element name="CONF">
		<xs:annotation>
			<xs:documentation>CONF Tag is the root of all tags.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HEXMOD"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DLL">
		<xs:annotation>
			<xs:documentation>DLL tag contains NAME attribute which is to be provided with the dllname and CFG contains the name of the configuration file on which the dll acts.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="NAME" type="xs:string" use="required"/>
			<xs:attribute name="CFG" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ERRMOD">
		<xs:annotation>
			<xs:documentation>ERRMOD contains information on the logging of messages to log file,logging of messages to console and aborting of the program</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="LOG"/>
				<xs:element ref="MSGLOG" minOccurs="0"/>
				<xs:element ref="MSGCONSOLE" minOccurs="0"/>
				<xs:element ref="PROGABORT" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Removed from Version 3.1.1.0 as not used />
	<xs:element name="EXCEPTIONAREA">
		<xs:complexType>
			<xs:attribute name="FROM" type="exhexBinary" use="required"/>
			<xs:attribute name="TO" type="exhexBinary" use="required"/>
		</xs:complexType>
	</xs:element-->
	<!--xs:element name="FILLPATTERN">
		<xs:annotation>
			<xs:documentation>FILLPATTERN contains the information on the fillpatern value in the VALUE attribute</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="VALUE" type="exFillBinary" default="0xFF"/>
		</xs:complexType>
	</xs:element-->
	<xs:element name="GENERAL">
		<xs:annotation>
			<xs:documentation>GENERAL tag contains general information that which is to be shared by all modules</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TRANSLATEADDRESS" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="SEGMENTATOSEGMENT8" type="xs:boolean" use="optional" default="true"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="DEF_FILLPATTERN" minOccurs="0">
					<xs:annotation>
						<xs:documentation>This value will overwrite the default fill pattern over whole file. For the ranges not defined in DEF_RANGE, this value will be chosen. If this is not provided, 0xFF will be used as default.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="VALUE" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="DEF_RANGE" minOccurs="0" maxOccurs="unbounded"/>
				<!--xs:element ref="FILLGAPS" maxOccurs="unbounded"/-->
				<!-- Removed from version 3.1.1.1 date 9.03.2004>
				<xs:element ref="FILLPATTERN" minOccurs="0"/-->
				<!-- Removed from Version 3.1.1.0 as not used />
				<xs:element ref="EXCEPTIONAREA" minOccurs="0" maxOccurs="unbounded"/-->
                
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DEF_RANGE">
		<xs:annotation>
			<xs:documentation>DEF_RANGE tag contains all the ranges which have to be processed.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="START" type="exhexBinary" use="required"/>
			<xs:attribute name="LEN" type="exhexBinary" use="required"/>
			<xs:attribute name="FILLPATTERN" type="xs:string" use="optional"/>
			<xs:attribute name="FILLGAP" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!--element name="FILLGAPS">
		<xs:complexType>
			<xs:attribute name="START" type="exhexBinary" use="required"/>
			<xs:attribute name="LEN" type="exhexBinary" use="required"/>
			<xs:attribute name="FILLPATTERN" type="exFillBinary" use="required"/>
		</xs:complexType>
	</xs:element-->
	<xs:element name="HEXMOD">
		<xs:annotation>
			<xs:documentation>Hexmod Tag is the basic tag for all the modules.This tag always comes after CONF tag. It represents the following content is for Hexmod tool to process</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ERRMOD" minOccurs="0"/>
				<xs:element ref="MAINMOD"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LOADDLL">
		<xs:annotation>
			<xs:documentation>LOADDLL element has list of  DLL elements which contain information on the DLLLs to be loaded.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DLL" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LOG">
		<xs:annotation>
			<xs:documentation>LOG Tag is used to specify the Log file name in the FILE attribute.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="FILE" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FILEIN">
		<xs:annotation>
			<xs:documentation>FILEIN Tag is used to specify the Input file in the NAME attribute,the output filename in the OUTFILE attribute and also IGNORELINECHKSUM to specify if the line checksum has to ignored or not.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="TYPE" type="filetype" use="required"/>
			<xs:attribute name="IGNORELINECKS" type="xs:boolean" default="false"/>
			<xs:attribute name="NAME" type="xs:string" use="required"/>
			<xs:attribute name="OUTFILE" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FILELIST">
		<xs:annotation>
			<xs:documentation>FILELIST contains the Elements FILEIN and DLL.FILEIN can occur any number of times but should occur atleast once and so is DLL but DLL's NAME attribute cannot be BaseIO</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FILEIN" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element ref="DLL" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MAINMOD">
		<xs:annotation>
			<xs:documentation>MAINMOD determines the main sequnence of operations hexmod excecutes. It has to contain LOADDLL which determines what dlls have to be loaded.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GENERAL" minOccurs="0"/>
                <xs:element ref="LOADDLL" minOccurs="0"/>
                <xs:choice>
					<xs:element ref="FILELIST" minOccurs="0" maxOccurs="1"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MSGCONSOLE">
		<xs:annotation>
			<xs:documentation>MSGCONSOLE is the level which has to be logged to the console - 1 stands for INFO,2 stands for WARNING,3 stands for error.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="LVL" type="exLvl" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="MSGLOG">
		<xs:annotation>
			<xs:documentation>MSGLOG is the level which has to be logged to the log file - 1 stands for INFO,2 stands for WARNING,3 stands for error.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="LVL" type="exLvl" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PROGABORT">
		<xs:annotation>
			<xs:documentation>PROGABORT is the level which exits the program  - 2 stands for WARNING,3 stands for error.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="LVL" type="exLvl2" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="exhexBinary">
		<xs:annotation>
			<xs:documentation>This is a user datatype where the string has to begin with 0x and the number must be hexadecimal</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
			<xs:minLength value="3"/>
			<xs:pattern value="[0]x[a-fA-F0-9]*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="exFillBinary">
		<xs:restriction base="xs:string">
			<xs:maxLength value="4"/>
			<xs:minLength value="3"/>
			<xs:pattern value="[0]x[a-fA-F0-9]*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="exLvl">
		<xs:restriction base="xs:unsignedByte">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="exLvl2">
		<xs:restriction base="xs:unsignedByte">
			<xs:minInclusive value="2"/>
			<xs:maxInclusive value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="filetype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="S19"/>
			<xs:enumeration value="IHEX"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== abc2cobsubasrikavya/100FIT_BOBE/BOBE_X150/BoschInputs/hexmodx/resources/samples/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<CONF xmlns="www.rbin.com/mds-1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="www.rbin.com/mds-1 file:///C:/Program%20Files/Bosch/Hexmod/schemas/rules.xsd">
	<HEXMOD>
		<ERRMOD>
			<LOG FILE="hexmodX_XML.log"/>
			<MSGLOG LVL="1"/>
			<MSGCONSOLE LVL="1"/>
			<PROGABORT LVL="3"/>
		</ERRMOD>
		<MAINMOD>
			<LOADDLL>
				<DLL NAME="BaseIO" CFG="Input.xml"/>
				<DLL NAME="InfoBlock" CFG="InfoBlock.xml"/>
				<DLL NAME="BaseIO" CFG="Output.xml"/>
			</LOADDLL>
		</MAINMOD>
	</HEXMOD>
</CONF>
